### PR TITLE
Format ssn & tel text input

### PR DESCRIPTION
**Pull request by noahsug**
Note: I'm using prettier which decided to do a bunch of formatting changes. I think the changes are fairly reasonable, so hopefully you're cool with it! It's super nice never having to worry about formatting or missing semicolons :)

 - added default mask for ssn
 - renamed withDebouncedRenderer to withChangeOnBlurRenderer
 - moved format logic into withChangeOnBlurRenderer like we do with the parsing logic, this way it's generic
 - added tests

If we want to change withChangeOnBlurRenderer to actually use the debounce method instead of waiting for a blur we could add that in another CL, but since we're formatting on blur it made sense to keep it as is for now.

### CODE REVIEW

**Comment by DeadHeadRussell** [comment]
Logic changes look mostly good, though it's a bit hard to tell through all the prettier changes (also, I'm hella tired).
Tests all look good.

I have a couple thoughts on the prettier.  I'd prefer the trailing comma settings to be set to "es5" so that function arguments don't have trailing commas.  It was throwing me off in a few places and I don't see a solid use case for it.  I do like the trailing commas in arrays and objects though.

Also, is there a way to add parentheses around JSX ala AirBnB?  I was really liking that style for readability after switching to it recently.   I didn't see a setting that would work, but only took a quick glance (I'm  assuming you're using https://github.com/prettier/prettier#options ?)

Also, if we'll be using this prettier, could you add it to the dev packages / include a config file for it so we get consistent settings?

**Comment by noahsug** [comment]
I've added the prettier script via "npm run format <filePath>" and updated the files to use the es5 commas.

Prettier does keep the AirBnB parentheses when a return statement is used, which I think is the use case that actually matters (since the point is to keep the jsx indentation intact).

E.g.

// Ewww, prettier will insert parens in this case.
function b() {
  return <div>
        <bob>
      </div>
}

// This looks fine to me (indentation is intact), and prettier will allow this.
const b = () =>
  <div>
    <boo>
  </div>

**Comment by noahsug** [comment]
Herm looks like github comments don't allow me to use tags. Let me try that again:

// Ewww, prettier will insert parens in this case.
function b() {
return div
......text
..../div
}

// This looks fine to me (indentation is intact), and prettier will allow this.
const b = () =>
....div
......text
..../div

**Comment by noahsug** [comment]
But to answer your question,  I unfortunately don't see a way to change this behavior in prettier :(

**Comment by DeadHeadRussell** [comment]
```
return <div>
</div>
```

**Pull request merged**
